name: app_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  dotenv: ^4.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  dropdown_button2: ^2.3.9
  custom_sliding_segmented_control: ^1.8.3
  omni_datetime_picker: ^1.1.0
  animated_custom_dropdown: ^3.1.0
  accordion: ^2.6.0
  quickalert: ^1.1.0
  loading_animation_widget: ^1.2.1
  circular_menu: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  timeline_list: ^0.0.6
  awesome_dialog: ^3.2.1
  permission_handler: ^11.3.1
  file_picker: ^10.3.2
  mime: ^1.0.5
  percent_indicator: ^4.2.3
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  flutter_pdfview: ^1.3.2
  page_flip: ^0.2.3
  widget_zoom: ^0.0.4
  syncfusion_flutter_pdfviewer: ^30.2.7
  easy_image_viewer: ^1.5.0
  pinch_zoom: ^2.0.0
  calendar_view: ^1.2.0
  calendar_date_picker2: ^1.1.5
  date_picker_plus: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/image/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
